config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :recipes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :recipes, only: %i[show index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def contentful
    Contentful::Client.new(
      access_token: ENV['CONTENTFUL_ACCESS_TOKEN'],
      space: ENV['CONTENTFUL_SPACE_ID'],
      dynamic_entries: :auto,
      raise_errors: true,
      raise_for_empty_fields: false
    )
  end
end

app/controllers/concerns/contentful_rescuer.rb
# frozen_string_literal: true

module ContentfulRescuer
  extend ActiveSupport::Concern

  included do
    rescue_from 'Contentful::Error' do |_exception|
      render file: 'public/422.html', status: 422, layout: false
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  include ContentfulRescuer

  CONTENT_TYPE = 'recipe'
  PER_PAGE = 2

  def index
    @recipes = RecipeDecorator.decorate_collection(recipes)
  end

  def show
    if recipe.present?
      @recipe = RecipeDecorator.decorate(recipe)
    else
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end

  private

  def recipe
    if params[:id].present?
      contentful.entry(params[:id], content_type: CONTENT_TYPE)
    end
  end

  def recipes
    contentful.entries(content_type: CONTENT_TYPE, limit: PER_PAGE, skip: skipped)
  end

  def skipped
    PER_PAGE * current_page
  end

  def current_page
    if params[:page].present?
      params[:page].to_i - 1
    else
      0
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def markdown
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<h3>Recipes</h3>
<div class="divider"></div>

<div class="row">
  <% @recipes&.each do |recipe| %>
      <div class="col s12 m6">
        <div class="card">
          <div class="card-image">
            <img src="<%= recipe.photo_url %>" >
            <span class="card-title"><%= recipe.title %></span>
          </div>
          <div class="card-action">
            <%= link_to 'Recipe Details', recipe_path(recipe.id) %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<%= paginate @recipes %>

app/views/recipes/show.html.erb
<h3>
  <a class="waves-effect waves-light" href= "<%=recipes_path%>" >
    <i class="material-icons medium">keyboard_arrow_left</i>
  </a>
  <%= @recipe.title %>
</h3>
<div class="divider"></div>

<div class="row">
  <div class="col s12 m12">
    <div class="card">
      <div class="card-image">
        <img src="<%= @recipe.photo_url %>" >
      </div>
      <div class="card-content">
        <div class="row">
          <%if @recipe.chef.present? %>
            <div class="chip left">
              <%=@recipe.chef_name%>
            </div>
          <%end%>
        </div>
        <p><%= @recipe.parsed_description %></p>
      </div>
      <div class="card-action">
        <div class="row">
          <% @recipe.tags&.each do |tag| %>
            <span class="tag badge left"><%=tag.name%></span>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>